name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18" # Use Node 18 or your preferred stable version
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test -- --watchAll=false
